#pragma once

enum FoveaShape
{
    FOVEA_SHAPE_UNIFORM,
    FOVEA_SHAPE_CIRCLE,
    FOVEA_SHAPE_SPLITHORIZONTALLY,
    FOVEA_SHAPE_SPLITVERTICALLY,
};

enum FoveaInputType
{
    FOVEA_INPUT_TYPE_NONE,
    FOVEA_INPUT_TYPE_PROCEDURAL,
    FOVEA_INPUT_TYPE_MOUSE,
};
